kind: pipeline
name: unittest

concurrency:
  limit: 1

steps:
- name: flake8
  image: alpine/flake8:3.7.7
  commands:
  - flake8

- name: unittest
  image: python:3.9.2-buster
  commands:
  - apt-get update -yqq
  - pip install flake8 pipenv > /dev/null
  - pipenv install --system --deploy --ignore-pipfile
  - polyglot download --dir /root/polyglot_data/ ner2.en ner2.de  ner2.ar ner2.bg ner2.ca ner2.cs ner2.da ner2.el ner2.es ner2.et ner2.fa ner2.fi ner2.fr ner2.he ner2.hi ner2.hr ner2.hu ner2.id ner2.it ner2.ja ner2.ko ner2.lt ner2.lv ner2.ms ner2.nl ner2.no ner2.pl ner2.pt ner2.ro ner2.ru ner2.sk ner2.sl ner2.sr ner2.sv ner2.th ner2.tl ner2.tr ner2.uk ner2.vi ner2.zh
  - polyglot download --dir /root/polyglot_data/ embeddings2.en embeddings2.de embeddings2.ar embeddings2.bg embeddings2.ca embeddings2.cs embeddings2.da  embeddings2.el embeddings2.et embeddings2.fa embeddings2.fi embeddings2.he embeddings2.hi embeddings2.hr embeddings2.hu embeddings2.id embeddings2.ja embeddings2.ko embeddings2.lt embeddings2.lv embeddings2.ms embeddings2.no embeddings2.ro embeddings2.sk embeddings2.sl embeddings2.sr embeddings2.sv embeddings2.th embeddings2.tl embeddings2.tr embeddings2.uk embeddings2.vi embeddings2.zh
  - pip install -e .
  - cp config/default.conf config/app.conf
  - pytest -v tests/unit_test.py

---
kind: pipeline
name: publish

concurrency:
  limit: 1

trigger:
  status:
  - success
  event:
  - push
  - tag

depends_on:
- unittest

steps:

- name: build base docker image
  image: plugins/docker
  settings:
    repo: liquidinvestigations/hoover-snoop2
    auto_tag: true
    auto_tag_suffix: base
    dockerfile: Dockerfile.base
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
    branch:
    - master

- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/nlp-service
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    branch:
      exclude:
      - dependabot/**

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/nlp-service
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: integration-test

depends_on:
- publish

concurrency:
  limit: 1

steps:
- name: run tests
  image: liquidinvestigations/nlp-service:${DRONE_COMMIT_BRANCH}
  pull: always
  commands:
  - pytest -v tests/integration_test.py

---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password
