kind: pipeline
name: publish

concurrency:
  limit: 1

trigger:
  status:
  - success
  event:
  - push
  - tag

steps:
- name: flake8
  image: alpine/flake8:3.7.7
  commands:
  - flake8

- name: build base docker image
  image: plugins/docker
  settings:
    repo: liquidinvestigations/nlp-service
    tags: latest-base
    #auto_tag_suffix: base
    dockerfile: Dockerfile.base
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
  #  branch:
  #  - master

- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/nlp-service
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    branch:
      exclude:
      - dependabot/**

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/nlp-service
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: integration-test

depends_on:
- publish

concurrency:
  limit: 1

steps:
- name: run tests
  image: liquidinvestigations/nlp-service:${DRONE_COMMIT_BRANCH}
  pull: always
  commands:
  - apt-get update -yqq
  - pip install flake8 pipenv > /dev/null
  - pipenv install --system --deploy --ignore-pipfile
  - polyglot download --dir /root/polyglot_data/  ner2.ro
  - polyglot download --dir /root/polyglot_data/beddings2.da embeddings2.ro
  - python -m spacy download xx_ent_wiki_sm
  - python -m spacy download en_core_web_sm
  - cp config/default.conf config/app.conf
  - py.test


---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password
